---

- name: Install Odoo dependencies
  apt:  pkg={{ item }}
        state=installed
        update_cache={{ odoo_apt_update_cache }}
        cache_valid_time={{ odoo_apt_cache_valid_time }}
  with_items: "{{ odoo_debian_packages }}"

- name: Install Odoo dependencies (PyPi)
  pip: name={{ item }}
  with_items: "{{ odoo_pypi_packages }}"

- name: Generate Odoo configuration file
  template: src=odoo-{{ odoo_version }}.conf dest={{ odoo_config_file }}
        owner={{ odoo_user }} group={{ odoo_user }} mode=0600
        force={{ odoo_force_config and 'yes' or 'no' }}
        backup=yes
  notify: Restart Odoo

- name: Generate Odoo init script
  template: src=odoo-{{ odoo_version }}.init dest=/etc/init.d/{{ odoo_service }}
        owner=root group=root mode=0755
        force={{ odoo_force_config and 'yes' or 'no' }}
        backup=yes
  notify: Restart Odoo
