dynamic_inventory_file: "inventory.assets"
dynamic_inventory_groups: 
    - digitalocean
    - aws

# odoo dependencies
odoo_debian_packages:
    - python-dev
    - python-psycopg2
    - python-simplejson
    - python-lxml
    - python-tz
    - python-imaging
    - python-yaml
    - python-reportlab
    - python-mako
    - python-pychart
    - python-werkzeug
    - python-dateutil
    - python-unittest2
    - python-mock
    - python-openid
    - python-docutils
    - python-feedparser
    - python-gdata
    - python-jinja2
    - python-psutil
    - python-pydot
    - python-webdav
    - python-vatnumber
    - python-vobject
    - python-xlwt
    - python-ldap
    - python-openssl
    - python-egenix-mxdatetime
    - python-zsi
    - python-requests
    - python-decorator
    - python-passlib
    - python-babel
    - python-gevent
      #- python-pypdf
